# --- GitHub Pages (Just the Docs) ---
title: "Montaje y Mantenimiento de Equipos Informáticos — Apuntes y recursos"
description: "Documentación del módulo Montaje y Mantenimiento"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Project site (URL: https://TU_USUARIO.github.io/MontajeSmr/)
baseurl: "/MontajeSmr"

# Logo (coloca tu propio logo en assets/logo.png si quieres)
logo: "/assets/logo.png"

# Opcionales de navegación/buscador
search_enabled: true
# aux_links:
#   "Ver en GitHub":
#     - "https://github.com/TU_USUARIO/MontajeSmr"

 




# --- GitHub Pages (Just the Docs) ---
title: "MontajeSmr — Apuntes y recursos"
description: "Documentación del módulo Montaje y Mantenimiento"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Project site (URL: https://TU_USUARIO.github.io/MontajeSmr/)
baseurl: "/MontajeSmr"

# Logo (coloca tu propio logo en assets/logo.png si quieres)
logo: "/assets/logo.png"

# Opcionales de navegación/buscador
search_enabled: true
# aux_links:
#   "Ver en GitHub":
#     - "https://github.com/TU_USUARIO/MontajeSmr"



